# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Codicat < Formula
  desc "Display directory tree and file contents from git repositories for llm"
  homepage "https://github.com/inakam/codicat"
  url "https://github.com/inakam/codicat/archive/refs/tags/v0.1.0.tar.gz"
  sha256 "1ee6f27abc23a2c285904a655a3aef7f65f0b59f85fd517548b49aabfad1145e"

  on_macos do
    on_intel do
      url "https://github.com/inakam/codicat/releases/download/v0.1.0/codicat-0.1.0-darwin-amd64.tar.gz"
      sha256 "afa470e52e9a5069fef485c1c2df82f2cc27702a2a139ce0fe1bc91396889603"
    end

    on_arm do
      url "https://github.com/inakam/codicat/releases/download/v0.1.0/codicat-0.1.0-darwin-arm64.tar.gz"
      sha256 "79716e9ec33c3096b0958d1aa416e296bf01a7bb36fd3962dbd3181b3aeb19c8"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/inakam/codicat/releases/download/v0.1.0/codicat-0.1.0-linux-amd64.tar.gz"
      sha256 "c7dddb719bd98269f1abd4c8debf3caec8c84cc3baeea73f16ddad4f2a67b1f7"
    end

    on_arm do
      url "https://github.com/inakam/codicat/releases/download/v0.1.0/codicat-0.1.0-linux-arm64.tar.gz"
      sha256 "33be87080c21ea42a7d86c89b93714a1e094eb037dcfb33a49e893c9e620bbbe"
    end
  end

  def install
    bin.install "codicat"
  end
end
