# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Codicat < Formula
  desc "Display directory tree and file contents from git repositories for llm"
  homepage "https://github.com/inakam/codicat"
  url "https://github.com/inakam/codicat/archive/refs/tags/v0.1.3.tar.gz"
  sha256 "bb5d43ac3a6cd15e6bd0b4a79996e3c2267f2231d634d37b323a3bb1765cb735"

  on_macos do
    on_intel do
      url "https://github.com/inakam/codicat/releases/download/v0.1.3/codicat-0.1.3-darwin-amd64.tar.gz"
      sha256 "5228bae7f6f03a553e839037ec0462e0d92473b0908d7a1b6e820d8e1b3ea31a"
    end

    on_arm do
      url "https://github.com/inakam/codicat/releases/download/v0.1.3/codicat-0.1.3-darwin-arm64.tar.gz"
      sha256 "ccdf88efcde305492aac2fc535c3686726391676667db6967de0725857745672"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/inakam/codicat/releases/download/v0.1.3/codicat-0.1.3-linux-amd64.tar.gz"
      sha256 "24ad7b9bc6fe98367504367a734c4c68fe62990e59aca3ff8c7f9089ca9c9613"
    end

    on_arm do
      url "https://github.com/inakam/codicat/releases/download/v0.1.3/codicat-0.1.3-linux-arm64.tar.gz"
      sha256 "d75049203b9f8401bbc1d08340fe574d1ddcbdb3697c28cfd79624d06b093cdf"
    end
  end

  def install
    bin.install "codicat"
  end
end
